version: '3.8'

services:
  ont-amplicon-phase:
    build: .
    image: ont-amplicon-phase:latest
    container_name: ont-amplicon-pipeline
    volumes:
      # Map host data to container
      - ${DATA_DIR:-/EBSDataDrive}:/EBSDataDrive
      - ${RESULTS_DIR:-./results}:/EBSDataDrive/ONT/Runs/results
    environment:
      # Override defaults if needed
      - ONT_BASE_DATA_DIR=/EBSDataDrive/ONT/Runs
      - ONT_SOFTWARE_DIR=/EBSDataDrive/software
      - ONT_S3_BUCKET=${ONT_S3_BUCKET:-nswhp-gaia-poc-pl}
      - ONT_S3_PREFIX=${ONT_S3_PREFIX:-ONT}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - ONT_LOG_LEVEL=INFO
    working_dir: /app
    command: ["ont-amplicon-phase", "--help"]

  # Development service
  ont-amplicon-dev:
    build: .
    image: ont-amplicon-phase:latest
    container_name: ont-amplicon-dev
    volumes:
      - ./src:/app/src
      - ${DATA_DIR:-/EBSDataDrive}:/EBSDataDrive
      - ${RESULTS_DIR:-./results}:/EBSDataDrive/ONT/Runs/results
    environment:
      - ONT_BASE_DATA_DIR=/EBSDataDrive/ONT/Runs
      - ONT_SOFTWARE_DIR=/EBSDataDrive/software
      - ONT_LOG_LEVEL=DEBUG
    working_dir: /app
    command: ["bash"]
    stdin_open: true
    tty: true