version: '3.8'

services:
  gui-ampmap:
    image: javadj/gui_ampmap:latest
    network_mode: "host"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./config:/app/config
    environment:
      - FLASK_ENV=production
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5001
    restart: unless-stopped